### ISSUE TITLE
Sort order of publications section

### ISSUE THREAD

**Issue by skbly7** [skbly7/serc#1]
Issue
The older publications within same year are coming above the newer publications

Reason
The year information is only present, and no date information to keep sorting properly.

Probable Solution/Hack
Keep the publications sorted by year, followed by sorting using the ID of the row of publication, which will not be exactly accurate, but can give lesser errors.

**Comment by yash-iiith** [comment]
Sir,
     The code below seems to solve the problem. Please verify.


```python
for key in publications_organized:
        s=sorted(publications_organized[key], key=lambda x: x.published_year, reverse=True)
        f=[]
        p=[]
        k=s[0].published_year
        for l in s:
        	if l.published_year == k:
        		f.append(l)
        	else:
        		m=sorted(f, key=lambda x: x.id, reverse=True)
        		for g in m:
        			p.append(g)
        		f=[]
        		f.append(l)
        		k=l.published_year
        m=sorted(f, key=lambda x: x.id, reverse=True)
        for g in m:
        	p.append(g)
        publications_organized[key]=p
```

**Comment by skbly7** [comment]
This long code isn't required, if can be done by editing one single line. Check the comment on pull request ( #2  ).

**Comment by skbly7** [comment]
Fixed by above merge.
